name: composite-action

on:
  workflow_dispatch:
    inputs:
      deploymentType:
        description: 'Type of deployment'
        required: false
        default: 'SNAPSHOT'
        type: choice
        options:
        - MAJOR
        - MINOR
        - SNAPSHOT

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: farhan-TheITguy/composite-action@v3
        with:
          who-to-greet: 'Farhan'
          deployment-type: ${{ inputs.deploymentType }}
      - run: echo version ${{ steps.foo.outputs.version }}
        shell: bash
