name: Export ENV
on:
  workflow_dispatch:
jobs:
  export_env:
    runs-on: ubuntu-latest
    name: Testing the exported env
    steps:
      - name: Checkout the variable repo
        id: step1
        uses: actions/checkout@master
        with:
          repository: farhan-TheITguy/scripts
          token: ${{ secrets.pat }}
      - name: export env
        uses: krisalay/export-env@v1.0.0
        with:
          filename: .env
      - name: Print env
        run: echo "Owner = $owner"