name: Export ENV
on:
  push:
  workflow_dispatch:
jobs:
  export_env:
    runs-on: ubuntu-latest
    name: Testing the exported env
    steps:
      - name: Checkout the variable repo
        id: step1
        uses: actions/checkout@master
        with:
          repository: farhan-TheITguy/scripts
          token: ${{ secrets.pat }}
      - name: Export variable
        run: echo "::set-env name=owner::farhan"
      - name: Print env
        run: echo "Owner = $owner"
  print:
    runs-on: ubuntu-latest
    name: Testing the exported env
    needs:
      - export_env
    steps:
      - name: Print env
        run: echo "Owner = $owner"