name: output-pipeline

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  prereq:
    runs-on: ubuntu-latest
    steps:
      - name: Save state
        id: save_state
        run: echo "owner=farhan" >> $GITHUB_STATE
      - name: Set output
        id: save_output
        run: echo "owner=farhan" >> $GITHUB_OUTPUT
      - name: print state
        run: echo "${{steps.save_state.outputs.owner}}"
      - name: print output
        run: echo "${{steps.save_output.outputs.owner}}"
  build:
    runs-on: ubuntu-latest
    needs: prereq
    steps:
      - name: print output
        run: echo "${{needs.prereq.steps.save_output.outputs.owner}}"
        
