name: output-pipeline

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Save state
        run: echo "owner=farhan" >> $GITHUB_STATE
      - name: Set output
        run: echo "owner=farhan" >> $GITHUB_OUTPUT
      - name: print state/output
        run: echo "${env.owner}"
        
