name: pipeline-sample

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.build.outputs.environment }}
      owner: ${{ steps.build.outputs.owner }}
      ver: ${{ steps.build.outputs.version }}
    steps:
      - name: Checkout the variable repo
        id: step1
        uses: actions/checkout@master
        with:
          repository: farhan-TheITguy/scripts
          token: ${{ secrets.pat }}

      - name: Before main repo checkout
        id: step2
        run: |
          ls -l
          pwd
          whoami
          
      - name: Importing the variables from the file
        run: |
          while read line; do
            echo "$line"
            line2=$(echo $line | tr '==' '::')
            echo $line2
            echo "$line" >> $GITHUB_ENV
            echo "::set-output name=$line2"
          done < vars/dev.env
          
      - uses: actions/checkout@v3

      - name: After main repo checkout
        run: |
          ls -l
          pwd
          whoami
          echo "Checking the variables from the file"
          echo "Environment = $environment"
          echo "Owner = $owner"
          echo "Version = $version"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: After main repo checkout
        env:
          env: ${{needs.build.outputs.env}}
          owner: ${{needs.build.outputs.owner}}
          ver: ${{needs.build.outputs.ver}}
        run: |
          ls -l
          pwd
          whoami
          echo "Checking the variables from the file"
          echo "Environment = ${env}"
          echo "Owner = ${owner}"
          echo "Version = ${ver}"
      
