name: pipeline-sample

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the variable repo
        uses: actions/checkout@master
        with:
          repository: farhan-TheITguy/scripts
          token: ${{ secrets.pat }}
          
      - uses: actions/checkout@v3

      - name: Before main repo checkout
        run: |
          ls -l
          pwd
          whoami
          
      - name: Importing the variables from the file
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < vars/dev.env

      - uses: actions/checkout@v3

      - name: After main repo checkout
        run: |
          ls -l
          pwd
          whoami
          echo "Checking the variables from the file"
          echo "Environment = $environment"
          echo "Owner = $owner"
          echo "Version = $version"
      
