name: pipeline-sample

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Importing the variable files
        uses: actions/checkout@master
        with:
          repository: orgname/reponame
          token: ${{ secrets.my_pat }}
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
