name: pipeline-sample

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Importing the variable files
        uses: actions/checkout@master
        with:
          repository: farhan-TheITguy/scripts
          token: ${{ secrets.pat }}
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          - ls -l
          - pwd
          - whoami
