name: simple-pipeline

on:
  workflow_dispatch:
    inputs:
      api_version:
        description: 'API version'
        required: true
        default: '2.5.3'
  schedule:
    - cron:  '*/1 * * * *'    # At every 15th minute

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print the version
        run: echo "api_version - ${{ github.event.inputs.api_version }}"
      
